### ISSUE TITLE
CSS: Schriftgröße viel zu klein

### ISSUE THREAD

**Issue by ebf1** [Okinkino/G1_UNIversal.github.io#12]
Im CSS ist keine Schriftgröße definiert (jedenfalls nicht im Master-Branch). Sollte man machen.

Ich würde das selbst fixen.

**Comment by st600540** [comment]
sollte in meinem Branch schon erledigt sein.

**Comment by ebf1** [comment]
Hab ich nicht gesehen ...

WIr haben jetzt, wie bereits unter https://github.com/Okinkino/G1_UNIversal.github.io/commit/949342331ca5824b510b24aa62253b3041a0f33b#commitcomment-36759416 geschrieben, ziemlich ähnliche Dinge getan.

Man beachte entsprechend auch 783c5b3.

Sollte diskutiert werden, welche Änderungen wovon man übernimmt. Das kann ja dann im Merging-Commit festgelegt werden ...
