### ISSUE TITLE
Links/Buttons Usable machen

### ISSUE THREAD

**Issue by st600540** [Okinkino/G1_UNIversal.github.io#14]
Derweil sind Buttons noch zu nichts zu gebrauchen ich habe einige ideen dazu. Schauts nachher für Refactoring noch drüber.

**Comment by st600540** [comment]
so ich hab mal 3 weitere Sections erstellt und ein bisschen Design umgeschrieben. Wie ich mich kenne wird es sicher eine Menge Rechtschreibfehler geben und ich würde mich freuen wenn jemand mal drüber schaut.

**Comment by ebf1** [comment]
Danke, @st600540 !
@Okinkino und ich haben bereits drüber geschaut. Passt sehr gut! Perfekt!
