### ISSUE TITLE
Contribution-Guide-Format

### ISSUE THREAD

**Issue by Okinkino** [Okinkino/G1_UNIversal.github.io#2]
Momentan schaut das Format vom Contribution-Guide ein bisschen Langweilig aus. Sinnvoll wäre ein Format wie dieses hier: https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md

**Comment by ghost** [comment]
Hab mal die Überschriften etwas formatiert wie in deinem Beispiel.
