### ISSUE TITLE
HTML5 tags statt ids

### ISSUE THREAD

**Issue by ghost** [Okinkino/G1_UNIversal.github.io#3]
Zurzeit verwenden wir ids wie "nav" und "header", aber seit HTML5 gibt es auch eigene HTML tags (`<nav>` und `<header>`), die bevorzugt werden sollten.

**Comment by st600540** [comment]
wie genau schaut des aus? Bsp pls find grad dazu nix

**Comment by ghost** [comment]
Ich hatte eigentlich zwei tags als beispiel in der issue aber ohne code block versucht github die tags anzuzeigen, habs jetzt behoben! ([hier mehr zu code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks), für einzelne wörter statt einen mehrzeiligen block braucht man nur zwei backticks!)

**Comment by ebf1** [comment]
See my comment on pull-request #4, i.e.: https://github.com/Okinkino/G1_UNIversal.github.io/pull/4#issuecomment-570093288
