### ISSUE TITLE
Website mit Inhalten anreichern

### ISSUE THREAD

**Issue by st600540** [Okinkino/G1_UNIversal.github.io#5]
Website sollte mit Inhalten angereichert werden... Basis sollte mal der Projektantragstext sein. Später sollte es aber trotzdem auf Rechtschreibung überprüfen.

**Comment by ebf1** [comment]
Warum nicht den Text unter "Pressemitteilung" aus der Projektabgabe verwenden?
Text siehe Projektabgabe-PDF, Seite 10-11. Wäre meiner Ansicht nach ganz gut für die Seite geeignet.

**Comment by ghost** [comment]
Klingt gut! @ebf1

**Comment by ebf1** [comment]
Maybe fixed by  9493423 and 783c5b3?
Especially after merging ...

**Comment by st600540** [comment]
Branch abandoned
