### ISSUE TITLE
Misleading/wrong tag usage <header> (cor. #5)

### ISSUE THREAD

**Issue by ebf1** [Okinkino/G1_UNIversal.github.io#7]
In der Branch [Stefan_Workbench] wird der Tag &lt;header&gt; falsch verwendet.
Hier wären die &lt;h*&gt;-Tags (&lt;h1&lt; bis &lt;h6&gt;) besser. Insbesondere &lt;h1&gt; und &lt;h2&gt;

Betreffend insbesondere auch #5

**Comment by st600540** [comment]
Sry war ein kleines Missverständnis wegen anderen issue

**Comment by ebf1** [comment]
Kein Problem!

**Comment by ghost** [comment]
Sollte durch 9abce02 und d9c367f korrigiert worden sein.
